stages:
 - lint
 - build
 - deploy

default:
  image: node:22-alpine

lint_frontend:
  stage: lint
  cache:
    - key:
        files:
          - node_modules.lock
      paths:
        - ./node_modules
  script:
    - yarn install
    - yarn run lint

build_frontend:
  stage: build
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - gcloud builds submit --config build.dev.yaml

deploy_mockserver:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - >-
      gcloud run deploy antimony-mockserver
      --image ghcr.io/smocker-dev/smocker:latest
      --allow-unauthenticated
      --region=europe-west1
      --memory=2Gi
      --ingress=all
      --port 8080
      --cpu=1

deploy_frontend:
  stage: deploy
  image: google/cloud-sdk:latest
  before_script:
    - echo ${GCLOUD_AUTH_KEY} > /tmp/gcloud-api.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-api.json
    - gcloud config set project antimony-438914
  script:
    - >-
      gcloud run deploy antimony-development
      --image europe-west1-docker.pkg.dev/antimony-438914/antimony/antimony-dev:latest
      --allow-unauthenticated
      --region=europe-west1
      --memory=2Gi
      --ingress=all
      --port 8100
      --cpu=1
