name: Build and Push Image

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-offline
jobs:

  publish-offline-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
       context: .
       push: true
       file: offline.Dockerfile
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
    
